In [72]:
# numpy provides import array and linear algebra utilities
import numpy as np

# the robotics toolbox provides robotics specific functionality
import roboticstoolbox as rtb

# spatial math provides objects for representing transformations
import spatialmath as sm

# 1.1 The Elementary Transform Sequence

In [73]:
# 변수로 Rotation Matrix 선언하기
rx_var = rtb.ET.Rx()
# 상수로 Rotation Matrix 선언하기
rx_cons = rtb.ET.Rx(np.pi / 2)

print(rx_var)
print(rx_cons)

Rx(q)
Rx(90°)


In [74]:
# Homogeneous Transformation Matrix 추출
transform_var = rx_var.A()
transform_cons = rx_cons.A()

print("="*30)
print("transform_var:")
print(transform_var)
print()

print("="*30)
print("transform_cons:")
print(transform_cons)
print()


# type 확인
print("="*30)
print("Type of transformation matrix:")
print(type(transform_var))
print()


# spatialmath package를 이용해서 SE3로 추출
sm_transform_var = sm.SE3(transform_var)
sm_transform_cons = sm.SE3(transform_cons)


print("="*30)
print("sm_transform_var: ")
print(sm_transform_var)
print()

print("="*30)
print("sm_transform_cons: ")
print(sm_transform_cons)
print()

# type 확인
print("="*30)
print("Type of SE3 transformation matrix:")
print(type(sm_transform_var))
print()

transform_var:
[[ 1.  0.  0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

transform_cons:
[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]

Type of transformation matrix:
<class 'numpy.ndarray'>

sm_transform_var: 
   1         0         0         0         
   0         1         0         0         
   0         0         1         0         
   0         0         0         1         


sm_transform_cons: 
   1         0         0         0         
   0         0        -1         0         
   0         1         0         0         
   0         0         0         1         


Type of SE3 transformation matrix:
<class 'spatialmath.pose3d.SE3'>



In [75]:
# 예시. x축으로 45도 회전하는 Homogeneous Transformation Matrix 구하기
q = np.pi / 4
Rotation_x = rtb.ET.Rx()
Transformation_mat = Rotation_x.A(q)
sm_Transformation_mat = sm.SE3(Transformation_mat)

print(f"Resulting SE3 at 45 degrees: \n{sm_Transformation_mat}")

Resulting SE3 at 45 degrees: 
   1         0         0         0         
   0         0.7071   -0.7071    0         
   0         0.7071    0.7071    0         
   0         0         0         1         



In [76]:
# Translation. x축으로의 translation(ex: prismatic joints)
q = 5 # 5m
Translation_x = rtb.ET.tx()

Transformation_mat = Translation_x.A(q)
# Transformation_mat = rtb.ET.tx(q)이렇게 직접 넣어도 됨

sm_Translation_x = sm.SE3(Transformation_mat)
print(sm_Translation_x)


   1         0         0         5         
   0         1         0         0         
   0         0         1         0         
   0         0         0         1         



In [77]:
# ETs of Franka Emika Panda

![FR3 ETS](image/Fr3.png)

In [78]:
E1 = rtb.ET.tz(0.333)
E2 = rtb.ET.Rz()
E3 = rtb.ET.Ry()
E4 = rtb.ET.tz(0.316)
E5 = rtb.ET.Rz()
E6 = rtb.ET.tx(0.0825)
E7 = rtb.ET.Ry(flip=True)
E8 = rtb.ET.tx(-0.0825)
E9 = rtb.ET.tz(0.384)
E10 = rtb.ET.Rz()
E11 = rtb.ET.Ry(flip=True)
E12 = rtb.ET.tx(0.088)
E13 = rtb.ET.Rx(np.pi)
E14 = rtb.ET.tz(0.107)
E15 = rtb.ET.Rz()

# We can make an ETS representing a Panda by incorprating all 15 ETs into an ETS
panda = E1 * E2 * E3 * E4 * E5 * E6 * E7 * E8 * E9 * E10 * E11 * E12 * E13 * E14 * E15

# View the ETS
print("panda = E1 * E2 * E3 * E4 * E5 * E6 * E7 * E8 * E9 * E10 * E11 * E12 * E13 * E14 * E15 : ")
print(panda)
print()

print("panda number of joints:", panda.n)
print()

print("panda number of ETs:", panda.m)
print()

print("specific ET -> panda[i], example panda[14]:", panda[14])
print()


print("panda.joints():")
print(panda.joints())
print()

print("All variable liks in the Panda ETS:")
print(panda.joint_idx)
print()

print("The first variable joint has a jindex :")
print(panda[1].jindex)
print()

panda = E1 * E2 * E3 * E4 * E5 * E6 * E7 * E8 * E9 * E10 * E11 * E12 * E13 * E14 * E15 : 
tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1) ⊕ tz(0.316) ⊕ Rz(q2) ⊕ tx(0.0825) ⊕ Ry(-q3) ⊕ tx(-0.0825) ⊕ tz(0.384) ⊕ Rz(q4) ⊕ Ry(-q5) ⊕ tx(0.088) ⊕ Rx(180°) ⊕ tz(0.107) ⊕ Rz(q6)

panda number of joints: 7

panda number of ETs: 15

specific ET -> panda[i], example panda[14]: Rz(q6)

panda.joints():
[ET.Rz(jindex=0), ET.Ry(jindex=1), ET.Rz(jindex=2), ET.Ry(jindex=3, flip=True), ET.Rz(jindex=4), ET.Ry(jindex=5, flip=True), ET.Rz(jindex=6)]

All variable liks in the Panda ETS:
<bound method BaseETS.joint_idx of [ET.tz(eta=0.333), ET.Rz(jindex=0), ET.Ry(jindex=1), ET.tz(eta=0.316), ET.Rz(jindex=2), ET.tx(eta=0.0825), ET.Ry(jindex=3, flip=True), ET.tx(eta=-0.0825), ET.tz(eta=0.384), ET.Rz(jindex=4), ET.Ry(jindex=5, flip=True), ET.tx(eta=0.088), ET.Rx(eta=3.141592653589793), ET.tz(eta=0.107), ET.Rz(jindex=6)]>

The first variable joint has a jindex :
0



# 1.2 Forward Kinematics

In [79]:
# 위의 ETs들을 모두 곱하면 base frame에서 나타낸 end effector의 frame을 나타낸다.
q = np.array([0, -0.3, 0, -2.2, 0, 2, 0.79])
fk = np.eye(4)

for et in panda:
    if et.isjoint:
        fk = fk @ et.A(q[et.jindex])
    else:
        fk = fk @ et.A()
print(sm.SE3(fk))

   0.7003   -0.7068    0.09983   0.4737    
  -0.7104   -0.7038    0         0         
   0.07027  -0.07092  -0.995     0.5155    
   0         0         0         1         



In [80]:
#fkine함수를 사용해도 된다
print(panda.fkine(q))
print()

print("Type of fkine: ")
print(type(panda.fkine(q)))
print()

print("If you want type of numpy -> eval(): ")
print(panda.eval(q))
print()

print("Type of eval: ")
print(type(panda.eval(q)))

   0.7003   -0.7068    0.09983   0.4737    
  -0.7104   -0.7038    0         0         
   0.07027  -0.07092  -0.995     0.5155    
   0         0         0         1         


Type of fkine: 
<class 'spatialmath.pose3d.SE3'>

If you want type of numpy -> eval(): 
[[ 7.00329021e-01 -7.06804465e-01  9.98334166e-02  4.73724040e-01]
 [-7.10353272e-01 -7.03845316e-01 -1.22464680e-16 -1.31037208e-17]
 [ 7.02672827e-02 -7.09169942e-02 -9.95004165e-01  5.15513206e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Type of eval: 
<class 'numpy.ndarray'>
